# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'darf_generation.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_DarfGeneration(object):
    def setupUi(self, DarfGeneration):
        if not DarfGeneration.objectName():
            DarfGeneration.setObjectName(u"DarfGeneration")
        DarfGeneration.resize(500, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DarfGeneration.sizePolicy().hasHeightForWidth())
        DarfGeneration.setSizePolicy(sizePolicy)
        DarfGeneration.setMinimumSize(QSize(500, 600))
        DarfGeneration.setMaximumSize(QSize(500, 600))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(216, 216, 216, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(235, 235, 235, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(108, 108, 108, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(144, 144, 144, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        brush6 = QBrush(QColor(255, 255, 220, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush7 = QBrush(QColor(0, 0, 0, 128))
        brush7.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush7)
#endif
        DarfGeneration.setPalette(palette)
        DarfGeneration.setFocusPolicy(Qt.NoFocus)
        self.verticalLayout = QVBoxLayout(DarfGeneration)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.backButtonLayout = QHBoxLayout()
        self.backButtonLayout.setObjectName(u"backButtonLayout")
        self.backButton = QPushButton(DarfGeneration)
        self.backButton.setObjectName(u"backButton")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)

        self.backButtonLayout.addWidget(self.backButton)

        self.errorLabel = QLabel(DarfGeneration)
        self.errorLabel.setObjectName(u"errorLabel")
        font1 = QFont()
        font1.setPointSize(13)
        self.errorLabel.setFont(font1)
        self.errorLabel.setStyleSheet(u"color: red")
        self.errorLabel.setAlignment(Qt.AlignCenter)

        self.backButtonLayout.addWidget(self.errorLabel)

        self.backButtonLayout.setStretch(0, 2)
        self.backButtonLayout.setStretch(1, 7)

        self.verticalLayout.addLayout(self.backButtonLayout)

        self.darfGenerationframe = QFrame(DarfGeneration)
        self.darfGenerationframe.setObjectName(u"darfGenerationframe")
        self.darfGenerationframe.setFrameShape(QFrame.StyledPanel)
        self.darfGenerationframe.setFrameShadow(QFrame.Raised)
        self.darfGenerationframeLayout = QVBoxLayout(self.darfGenerationframe)
        self.darfGenerationframeLayout.setObjectName(u"darfGenerationframeLayout")
        self.titleLabel = QLabel(self.darfGenerationframe)
        self.titleLabel.setObjectName(u"titleLabel")
        font2 = QFont()
        font2.setPointSize(30)
        self.titleLabel.setFont(font2)
        self.titleLabel.setAlignment(Qt.AlignCenter)
        self.titleLabel.setWordWrap(True)

        self.darfGenerationframeLayout.addWidget(self.titleLabel)

        self.progressBar = QProgressBar(self.darfGenerationframe)
        self.progressBar.setObjectName(u"progressBar")
        sizePolicy1.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy1)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet(u"QProgressBar {\n"
"    border: 10px solid grey;\n"
"    border-radius: 18px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: lightblue;\n"
"    border-radius: 18px;\n"
"    width: 10px;\n"
"    margin: 0.5px;\n"
"}")
        self.progressBar.setValue(24)

        self.darfGenerationframeLayout.addWidget(self.progressBar)

        self.captchaFrame = QFrame(self.darfGenerationframe)
        self.captchaFrame.setObjectName(u"captchaFrame")
        self.captchaFrame.setEnabled(True)
        self.captchaFrame.setFrameShape(QFrame.NoFrame)
        self.captchaFrame.setFrameShadow(QFrame.Raised)
        self.captchaFrameLayout = QVBoxLayout(self.captchaFrame)
        self.captchaFrameLayout.setObjectName(u"captchaFrameLayout")
        self.captchaFrameLayout.setContentsMargins(30, -1, 29, -1)
        self.captchaImage = QLabel(self.captchaFrame)
        self.captchaImage.setObjectName(u"captchaImage")
        self.captchaImage.setScaledContents(True)
        self.captchaImage.setAlignment(Qt.AlignCenter)

        self.captchaFrameLayout.addWidget(self.captchaImage)

        self.captchaInput = QLineEdit(self.captchaFrame)
        self.captchaInput.setObjectName(u"captchaInput")
        sizePolicy1.setHeightForWidth(self.captchaInput.sizePolicy().hasHeightForWidth())
        self.captchaInput.setSizePolicy(sizePolicy1)
        self.captchaInput.setAlignment(Qt.AlignCenter)

        self.captchaFrameLayout.addWidget(self.captchaInput)

        self.captchaButton = QPushButton(self.captchaFrame)
        self.captchaButton.setObjectName(u"captchaButton")
        sizePolicy1.setHeightForWidth(self.captchaButton.sizePolicy().hasHeightForWidth())
        self.captchaButton.setSizePolicy(sizePolicy1)
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setWeight(75)
        self.captchaButton.setFont(font3)

        self.captchaFrameLayout.addWidget(self.captchaButton)

        self.captchaFrameLayout.setStretch(0, 3)
        self.captchaFrameLayout.setStretch(1, 1)
        self.captchaFrameLayout.setStretch(2, 2)

        self.darfGenerationframeLayout.addWidget(self.captchaFrame)

        self.cpfFrame = QFrame(self.darfGenerationframe)
        self.cpfFrame.setObjectName(u"cpfFrame")
        self.cpfFrame.setEnabled(True)
        self.cpfFrame.setFrameShape(QFrame.NoFrame)
        self.cpfFrame.setFrameShadow(QFrame.Raised)
        self.cpfFrameLayout = QVBoxLayout(self.cpfFrame)
        self.cpfFrameLayout.setObjectName(u"cpfFrameLayout")
        self.cpfFrameLayout.setContentsMargins(30, -1, 30, -1)
        self.cpfInput = QLineEdit(self.cpfFrame)
        self.cpfInput.setObjectName(u"cpfInput")
        sizePolicy1.setHeightForWidth(self.cpfInput.sizePolicy().hasHeightForWidth())
        self.cpfInput.setSizePolicy(sizePolicy1)
        self.cpfInput.setInputMask(u"")
        self.cpfInput.setMaxLength(11)
        self.cpfInput.setFrame(True)
        self.cpfInput.setEchoMode(QLineEdit.Normal)
        self.cpfInput.setAlignment(Qt.AlignCenter)

        self.cpfFrameLayout.addWidget(self.cpfInput)

        self.stateList = QComboBox(self.cpfFrame)
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.addItem("")
        self.stateList.setObjectName(u"stateList")
        self.stateList.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.stateList.sizePolicy().hasHeightForWidth())
        self.stateList.setSizePolicy(sizePolicy1)
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush8 = QBrush(QColor(217, 216, 216, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush9 = QBrush(QColor(236, 235, 235, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush9)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush10 = QBrush(QColor(145, 144, 144, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush10)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush9)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush10)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush7)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush10)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush7)
#endif
        self.stateList.setPalette(palette1)
        self.stateList.setLayoutDirection(Qt.LeftToRight)
        self.stateList.setStyleSheet(u"QComboBox {padding-left: 20px}")
        self.stateList.setEditable(True)
        self.stateList.setMaxVisibleItems(99)
        self.stateList.setMaxCount(99)

        self.cpfFrameLayout.addWidget(self.stateList)

        self.cityInput = QLineEdit(self.cpfFrame)
        self.cityInput.setObjectName(u"cityInput")
        sizePolicy1.setHeightForWidth(self.cityInput.sizePolicy().hasHeightForWidth())
        self.cityInput.setSizePolicy(sizePolicy1)
        self.cityInput.setInputMask(u"")
        self.cityInput.setMaxLength(50)
        self.cityInput.setFrame(True)
        self.cityInput.setEchoMode(QLineEdit.Normal)
        self.cityInput.setAlignment(Qt.AlignCenter)

        self.cpfFrameLayout.addWidget(self.cityInput)

        self.cpfButton = QPushButton(self.cpfFrame)
        self.cpfButton.setObjectName(u"cpfButton")
        sizePolicy1.setHeightForWidth(self.cpfButton.sizePolicy().hasHeightForWidth())
        self.cpfButton.setSizePolicy(sizePolicy1)
        self.cpfButton.setFont(font3)

        self.cpfFrameLayout.addWidget(self.cpfButton)

        self.cpfFrameLayout.setStretch(0, 1)
        self.cpfFrameLayout.setStretch(1, 1)
        self.cpfFrameLayout.setStretch(2, 1)
        self.cpfFrameLayout.setStretch(3, 2)

        self.darfGenerationframeLayout.addWidget(self.cpfFrame)

        self.darfGenerationSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Preferred)

        self.darfGenerationframeLayout.addItem(self.darfGenerationSpacer)

        self.darfGenerationframeLayout.setStretch(0, 2)
        self.darfGenerationframeLayout.setStretch(1, 1)
        self.darfGenerationframeLayout.setStretch(2, 2)
        self.darfGenerationframeLayout.setStretch(3, 2)
        self.darfGenerationframeLayout.setStretch(4, 2)

        self.verticalLayout.addWidget(self.darfGenerationframe)


        self.retranslateUi(DarfGeneration)

        QMetaObject.connectSlotsByName(DarfGeneration)
    # setupUi

    def retranslateUi(self, DarfGeneration):
        DarfGeneration.setWindowTitle(QCoreApplication.translate("DarfGeneration", u"Consultar A\u00e7\u00f5es", None))
        self.backButton.setText(QCoreApplication.translate("DarfGeneration", u"<<", None))
        self.errorLabel.setText("")
        self.titleLabel.setText(QCoreApplication.translate("DarfGeneration", u"Preencha os dados...", None))
        self.captchaImage.setText(QCoreApplication.translate("DarfGeneration", u"IMAGE GOES HERE", None))
        self.captchaInput.setPlaceholderText(QCoreApplication.translate("DarfGeneration", u"SOLUTION", None))
        self.captchaButton.setText(QCoreApplication.translate("DarfGeneration", u"ENVIAR SOLU\u00c7\u00c3O", None))
        self.cpfInput.setText("")
        self.cpfInput.setPlaceholderText(QCoreApplication.translate("DarfGeneration", u"CPF", None))
        self.stateList.setItemText(0, QCoreApplication.translate("DarfGeneration", u"AL - ALAGOAS", None))
        self.stateList.setItemText(1, QCoreApplication.translate("DarfGeneration", u"AM - AMAZONAS", None))
        self.stateList.setItemText(2, QCoreApplication.translate("DarfGeneration", u"AP - AMAPA", None))
        self.stateList.setItemText(3, QCoreApplication.translate("DarfGeneration", u"BA - BAHIA", None))
        self.stateList.setItemText(4, QCoreApplication.translate("DarfGeneration", u"CE - CEARA", None))
        self.stateList.setItemText(5, QCoreApplication.translate("DarfGeneration", u"DF - DISTRITO FEDERAL", None))
        self.stateList.setItemText(6, QCoreApplication.translate("DarfGeneration", u"ES - ESPIRITO SANTO", None))
        self.stateList.setItemText(7, QCoreApplication.translate("DarfGeneration", u"GO - GOIAS", None))
        self.stateList.setItemText(8, QCoreApplication.translate("DarfGeneration", u"MA - MARANHAO", None))
        self.stateList.setItemText(9, QCoreApplication.translate("DarfGeneration", u"MG - MINAS GERAIS", None))
        self.stateList.setItemText(10, QCoreApplication.translate("DarfGeneration", u"MS - MATO GROSSO DO SUL", None))
        self.stateList.setItemText(11, QCoreApplication.translate("DarfGeneration", u"MT - MATO GROSSO", None))
        self.stateList.setItemText(12, QCoreApplication.translate("DarfGeneration", u"PA - PARA", None))
        self.stateList.setItemText(13, QCoreApplication.translate("DarfGeneration", u"PB - PARAIBA", None))
        self.stateList.setItemText(14, QCoreApplication.translate("DarfGeneration", u"PE - PERNAMBUCO", None))
        self.stateList.setItemText(15, QCoreApplication.translate("DarfGeneration", u"PI - PIAUI", None))
        self.stateList.setItemText(16, QCoreApplication.translate("DarfGeneration", u"PR - PARANA", None))
        self.stateList.setItemText(17, QCoreApplication.translate("DarfGeneration", u"RJ - RIO DE JANEIRO", None))
        self.stateList.setItemText(18, QCoreApplication.translate("DarfGeneration", u"RN - RIO GRANDE DO NORTE", None))
        self.stateList.setItemText(19, QCoreApplication.translate("DarfGeneration", u"RO - RONDONIA", None))
        self.stateList.setItemText(20, QCoreApplication.translate("DarfGeneration", u"RR - RORAIMA", None))
        self.stateList.setItemText(21, QCoreApplication.translate("DarfGeneration", u"RS - RIO GRANDE DO SUL", None))
        self.stateList.setItemText(22, QCoreApplication.translate("DarfGeneration", u"SC - SANTA CATARINA", None))
        self.stateList.setItemText(23, QCoreApplication.translate("DarfGeneration", u"SE - SERGIPE", None))
        self.stateList.setItemText(24, QCoreApplication.translate("DarfGeneration", u"SP - SAO PAULO", None))
        self.stateList.setItemText(25, QCoreApplication.translate("DarfGeneration", u"TO - TOCANTINS", None))

        self.cityInput.setText("")
        self.cityInput.setPlaceholderText(QCoreApplication.translate("DarfGeneration", u"CIDADE", None))
        self.cpfButton.setText(QCoreApplication.translate("DarfGeneration", u"GERAR", None))
    # retranslateUi

